name: myenv
channels:
  - bioconda
  - defaults
dependencies:
  - python=3.9.18
  - blas=1.0=mkl
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - cmake=3.26.4
  - expat=2.5.0
  - intel-openmp=2023.1.0
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libcurl=8.5.0
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.57.0
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libuv=1.44.2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numpy=1.26.3
  - openssl=3.0.13
  - pip=23.3.1
  - pytest
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - udunits2=2.2.25
  - wheel=0.41.2
  - xtermcolor=1.3
  - xz=5.4.5
  - zlib=1.2.13
  - zstd=1.5.5
